# Generated by Django 6.0.2 on 2026-02-22 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_records', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_records', to='accounts.account'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
