# Generated by Django 6.0.2 on 2026-02-22 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. GCB Current Account', max_length=100)),
                ('institution_name', models.CharField(blank=True, help_text='Specific Bank or Provider name', max_length=100, null=True)),
                ('account_type', models.CharField(choices=[('BANK', 'Bank Account'), ('MOMO', 'Mobile Money'), ('SUSU', 'Susu/Savings Group'), ('CASH', 'Physical Cash'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('provider', models.CharField(help_text='e.g., MTN, Telecel, GCB, Ecobank', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
